FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip

# FORCE CPU TORCH ONLY (this is the key fix)
RUN pip install --no-cache-dir \
    torch \
    --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]